[package]
name = "doom-ls"
version = "0.0.0"
edition = "2021"

authors = ["jerome-trc"]
description = "Language server for Doom DSLs"
homepage = "https://github.com/jerome-trc/doom-ls/"
keywords = ["doom", "ide", "language-server", "lsp"]
license = "MIT OR Apache-2.0"
publish = false
repository = "https://github.com/jerome-trc/doom-ls/"

[dependencies]
doomfront = { path = "../viletech/doomfront", features = [
	"zdoom"
] } # Temporary local path.
lsp-server = "0.7"
lsp-types = "0.94"
rustc-hash = "1.0.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
